openapi: 3.0.0
info:
  version: 1.0.0
  title: CSGO RCON Controller API
  description: API for sending batch RCON commands to a CSGO server
paths:
  /rcon:
    post:
      operationId: sendCommand
      summary: Send batch RCON commands
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                commands:
                  type: array
                  items:
                    type: string
              required:
                - commands
      responses:
        200:
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    command:
                      type: string
                    response:
                      type: string
        400:
          description: Invalid input
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
        500:
          description: Server error
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
